### ISSUE TITLE
Ops from std::ops or new ones.

### ISSUE THREAD

**Issue by paholg** [paholg/typenum#1]
In [peano](https://github.com/paholg/peano), I ended up using `Add`, `Mul`, etc. from `std::ops`. This lead to code like

```rust
/// Add to Zero (e.g. 0 + 3)
impl<Rhs> Add<Rhs> for Zero where Rhs: Peano {
    type Output = Rhs;
    #[allow(unused_variables)]
    fn add(self, rhs: Rhs) -> Self::Output { unreachable!() }
}
```

as all of these traits have an attached function that is not used. I have started `typenum` by making my own traits sans functions. I don't know whether this or using the `std::ops` traits is better.

**Comment by llogiq** [comment]
I think having our own is better, because the unused function is just baggage. If our types had actual instances, it'd be different, but here we are.

**Comment by paholg** [comment]
Yeah, my only concern is if someone needs to use both our `Add` and `std::ops::Add`, for example, it could get annoying. I guess they could do `extern crate typenum as tn` then have `Add` and `tn::Add` which wouldn't be terrible.

I imagine that most people using typenum will run into this, as I envision the main (only?) use case is creating custom types and many will want such operations.

**Comment by llogiq** [comment]
I was thinking about moving to actual n-tuples of bits. Granted, that only could encode N-bit numbers, but the operations would be easier and we could actually implement std::ops::* with actual (empty) implementations.

**Comment by paholg** [comment]
I've thought about doing that as well, but I struggle to see a use.

Why use a `UInt32`, for example, when `UInt` is more efficient for smaller numbers and can handle larger numbers?

I think it would also require a lot of boiler-platey macro stuff that doesn't sound super fun to write.

**Comment by llogiq** [comment]
True. And yes, using the default traits also has the benefit of inheriting their documentation and reducing our API surface a bit. Btw. you can just write:

```
/// Add to Zero (e.g. 0 + 3)
impl<Rhs> Add<Rhs> for UTerm where Rhs: Unsigned {
    type Output = Rhs;
    fn add(self, _: Rhs) -> Self::Output { unreachable!() }
}
```

no need for `#[allow(..)]`.

**Comment by paholg** [comment]
That is handy, thanks.

**Comment by llogiq** [comment]
My pleasure. Thinking more about it, let's just reuse the standard traits.
