### ISSUE TITLE
license clarification

### ISSUE THREAD

**Issue by ignatenkobrain** [paholg/typenum#100]
Cargo.toml says that the license is `MIT OR Apache-2.0`, however LICENSE file says it's just MIT. Could you clarify this?

**Comment by paholg** [comment]
Oops! I intended it to be dual licensed. I am not sure on the legality now that there are multiple contributors, but I would approve a PR that adds Apache-2.0 to the license file.

**Comment by ignatenkobrain** [comment]
@spotrh, do you have any recommendation here?

**Comment by spotrh** [comment]
Assuming that everyone who contributed did so under MIT, MIT permits "sublicensing", so adding the Apache 2.0 license as a choice is something that any recipient could do.

This means that while it would be polite to consult with the other contributors before adding a different license option, it is not legally required.

Please note: IANAL and this is not legal advice. If you require formal legal advice, you should retain counsel.

My suggestion would be to simply go ahead and make this change.

**Comment by droundy** [comment]
Sounds good to me.

**Comment by paholg** [comment]
Merged.
