### ISSUE TITLE
Build fails on windows when compiling with wasm-pack

### ISSUE THREAD

**Issue by bgourlie** [paholg/typenum#107]
typenum is a transient dependency for a project i'm working on, and it fails to build on Windows (specifically when building using wasm-pack) and it fails due to the unix-style directory separator used in the following two lines:

https://github.com/paholg/typenum/blob/master/src/lib.rs#L62

I'm able to fix this locally by editing the file in my cargo cache, changing replacing the forward slash with `\\`.

**Comment by droundy** [comment]
A better fix will be to use the path manipulation functions in the standard library.  Windows accepts UNIX-style directory separators, but I think it does not accept paths that mix the two kinds of separators.

**Comment by paholg** [comment]
Unfortunately, whatever the solution, it has to be done at compile time. I did a little investigation, and I can't come up with a better idea than adding a conditional compilation flag to check if on windows, and use `\\` there.

**Comment by bgourlie** [comment]
Appreciate the quick turnaround! If there were a desire to use a path manipulation functions, I think it would be possible to within a build.rs file, perhaps setting an environment variable that would subsequently be used by the `include!` macro. @llogiq's solution looks like it works just as well, so not sure if an ideal solution is worth the effort.
