### ISSUE TITLE
Have `to_X` methods be `const`

### ISSUE THREAD

**Issue by Lokathor** [paholg/typenum#112]
It seems that with the `const fn` feature becoming stable, all of the functions to extract the runtime value from a type-level number can become const.

**Comment by michaelsproul** [comment]
I wanted to have a go at implementing this, but it looks like some major groundwork in the Rust compiler is required.

Even on nightly, `const` functions in traits are disallowed (see [playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=c5438177ec0f89cf14ecd3b1cc0fb2e8) and [RFC-0911](https://github.com/rust-lang/rfcs/blob/master/text/0911-const-fn.md#alternatives))

Something along the lines of Varkor's proposal for `const` trait implementations would be required to make this feasible: https://varkor.github.io/blog/2019/01/11/const-types-traits-and-implementations-in-Rust.html

Even so, it's possible that const generics will land soon after, or even before const trait functions, at which point `typenum` would no longer be necessary (we could have real compile-time integers).

**Comment by paholg** [comment]
Trait functions still cannot be const, but typenum now has associated constants that perform the same function, so I'm going to consider this done.
