### ISSUE TITLE
Restricting methods to 

### ISSUE THREAD

**Issue by jrmuizel** [paholg/typenum#114]
I'm struggling to get a handle on how to use this library.

Is it possible to get something like this working:
```rust
struct Lock<Level> {
    level: Level,
}

impl<Level> Lock<Level> {
    fn lock<T>(&self, token: T) -> Level {
        return self.level;
    }
}
```
I'd like Lock to have some associated typenum and make it so that the `lock` method can only be called with a T that is <= Level. Is this possible? How would it be written?

**Comment by paholg** [comment]
Not knowing exactly what you're trying to do, here is an example:

```rust
use std::marker::PhantomData;
use typenum::{IsLessOrEqual, True, U3, U5, U7};

struct Lock<Level> {
    level: PhantomData<Level>,
}

impl<Level> Lock<Level> {
    fn new() -> Lock<Level> {
        Lock { level: PhantomData }
    }

    fn lock<T>(&self, _token: T)
    where
        T: IsLessOrEqual<Level, Output = True>,
    {
    }
}

fn main() {
    let x: Lock<U5> = Lock::new();

    x.lock(U3::new());

    // compiler error:
    // x.lock(U7::new());
}
```

In this case, `lock` is only defined when `T <= Level`, assuming both `T` and `Level` are desired to be type-level numbers.

**Comment by jrmuizel** [comment]
Thanks. This gives me enough to go on. I'll play around with it a bit and hopefully submit an example to the docs.

**Comment by jrmuizel** [comment]
Another question. Given the code that you provided above: 

Is there some way to write a function like:
```
fn do_stuff(token: T) {
    let x: Lock<Add1<T>> = Lock::new();
    x.lock(token);
}
```

i.e. what kind of type do I need T to be for so that Add1 works on it?

**Comment by paholg** [comment]
Looking at the definition for `Add1`: 

```rust
type Add1<A> = <A as Add<B1>>::Output;
```

so this should work:

```rust
fn do_stuff<T: Add<B1>>(token: T) {
    let x: Lock<Add1<T>> = Lock::new();
    x.lock(token);
}
```

**Comment by jrmuizel** [comment]
That gives:
```
  --> src/main.rs:26:7
   |
26 |     x.lock(token);
   |       ^^^^ the trait `typenum::Cmp<<Level as std::ops::Add<typenum::B1>>::Output>` is not implemented for `Level`
   |
   = help: consider adding a `where Level: typenum::Cmp<<Level as std::ops::Add<typenum::B1>>::Output>` bound
   = note: required because of the requirements on the impl of `typenum::IsLessOrEqual<<Level as std::ops::Add<typenum::B1>>::Output>` for `Level`
```

Is there some bounds that we can add that will also let it work with type constraints on `lock()`? 
Adding `Cmp<<Level as Add<typenum::B1>>::Output` complains about needing `typenum::private::IsLessOrEqualPrivate`

**Comment by paholg** [comment]
The error messages for typenum aren't great, but they usually at least tell you do to the right thing. This one does not.

You can track the constraint needed by looking at what lock does. In the end, this works:

```
fn do_stuff<T: Add<B1> + IsLessOrEqual<Add1<T>, Output = True>>(token: T) {
    let x: Lock<Add1<T>> = Lock::new();
    x.lock(token);
}
```
