### ISSUE TITLE
U1024 created twice

### ISSUE THREAD

**Issue by jteg68** [paholg/typenum#119]
When trying to build pijul the compiler complained of double declaration of U1024 and P1024. The responsible code seems to be in build/main.rs:

    fn main() {
        let highest: u64 = 1024;
    
        let first2: u32 = (highest as f64).log(2.0).round() as u32 + 1;
        let first10: u32 = (highest as f64).log(10.0) as u32 + 1;
        let uints = (0..(highest + 1))
            .chain((first2..64).map(|i| 2u64.pow(i)))
            .chain((first10..20).map(|i| 10u64.pow(i)));

As this is the first time ever looking at rust code I don't know all the details. Changing the line

    let uints = (0..(highest + 1))
to

    let uints = (0..(highest ))

allowed the compilation to proceed without warnings. This migth not be the correct fix.

Best regards,
Jörgen

**Comment by paholg** [comment]
This should have been fixed in #115. I have just pushed a new version to crates including that fix (Sorry, should have done that when it was first merged).

Could you confirm whether this is still broken with version 1.11.0?
