### ISSUE TITLE
Cross-compilation issue

### ISSUE THREAD

**Issue by mmatous** [paholg/typenum#124]
https://github.com/paholg/typenum/pull/108 broke cross-compilation (linux OS searching win paths). Original code works OK for linux, Win and linux->Win. Since the original issue (https://github.com/paholg/typenum/issues/107) was about wasm-pack, the commit should probably be reverted and issue brought to wasm-pack. It should behave like cargo and handle unix paths on any system.

**Comment by paholg** [comment]
Ugh. Without the change, compilation on Windows is broken. With it, cross-compilation to Windows is broken. Either way, it's an issue with typenum and not wasm-pack.

I don't see a good way to make this work.

For the current implementation, we use `target_os`. What we really care about, though, is the host os while building, and I see no reasonable way to get that.

We can (and do) build the path correctly in the build script, but how do we expose that to the build process? We could put it in a file, but then we have no way to include that file. We can put it in an environment variable, but, as far as I can tell, we can only do that for the current process.

I'm hoping there's a way to do this that I'm not seeing, and we can have this working in both environments.

**Comment by paholg** [comment]
Aha! I figured it out. There is a special cargo flag for this that I was missing.

https://stackoverflow.com/questions/51621642/how-to-specify-an-environment-variable-using-the-rustc-env-flag

**Comment by paholg** [comment]
You should have no problems with version 1.11.2, but please let me know if they persist.

**Comment by mmatous** [comment]
> Without the change, compilation on Windows is broken. 

Only with wasm-pack. `cargo build` worked fine. That's why I believe they should fix their inconsistent behavior. 
Anyway, thanks for fast fix. All good now.

**Comment by paholg** [comment]
Huh, interesting. I had thought it was broken for any building on Windows as the path would look like `C:\some\dir/test.rs`. In any case, it should be much more resilient now.
