### ISSUE TITLE
Unable to build using Bazel after recent `1.11.2` change

### ISSUE THREAD

**Issue by akhilles** [paholg/typenum#127]
Bazel's rust_rules can't pass the `TYPENUM_BUILD_OP` and `TYPENUM_BUILD_CONSTS` environment variables from build script to the compilation process. Would it be possible to just use the following instead?
```
include!(concat!(env!("OUT_DIR"), "/consts.rs"));
include!(concat!(env!("OUT_DIR"), "/op.rs"));
```

I realize Bazel isn't supported by this project but I think this change makes sense regardless of the build system being used. It works on linux and windows hosts (incl cross-compilation). Also, it seems to be standard practice among popular crates that use bindgen: https://crates.io/crates/bindgen/reverse_dependencies

**Comment by paholg** [comment]
Ugh. That's what I had, but it didn't work for another build process. I prefer the current method as it builds the paths correctly, and the path information is only in one place.

The answer might be to add a flag to switch to the includes you mentioned.

Out of curiosity, I know nothing about Bazel. Are you using it to invite rustc directly? Why not do use cargo? Or is there something else that prevents the use of the environment variables?

**Comment by akhilles** [comment]
Would a rustc cfg attr called `force_unix_path_separator` that is not set by default make sense? This can be used by non-Cargo build systems that invoke `rustc` directly.

Regarding Bazel, it provides build-reproducibility and fast incremental compilation. I've always found Cargo build to be dreadfully slow.

**Comment by paholg** [comment]
Yeah, that sounds good.

**Comment by TotempaaltJ** [comment]
For anyone looking, this is the Raze config that fixes it:

```toml
[raze.crates.typenum.'1.12.0']
gen_buildrs = true
additional_flags = [
    "--cfg=feature=\\\"force_unix_path_separator\\\"",
]
```
