### ISSUE TITLE
[feature-request] Implement IsZero trait

### ISSUE THREAD

**Issue by jerry73204** [paholg/typenum#132]
I tried to implement a trait that returns `True` if implemented typenum type is zero, otherwise returns false. It requires me distinguish `B0`, `U0`, `Z0` and non-of-above, and I found it's not trivial. Could you provide a `IsZero` trait based on bit operations?

Besides, `Value: IsEqual<B0> +: IsEqual<Z0> +: IsEqual<U0>` does not work. The compiler complains about this error.
```
the trait `typenum::type_operators::Cmp<typenum::bit::B0>` is not implemented for `typenum::uint::UTerm`
```

**Comment by seftontycho** [comment]
I suspect this is what you want: [https://docs.rs/typenum/latest/typenum/marker_traits/trait.Zero.html](https://docs.rs/typenum/latest/typenum/marker_traits/trait.Zero.html)

**Comment by GnomedDev** [comment]
Shouldn't this issue be closed, now that the feature is implemented?

**Comment by paholg** [comment]
Yep, thanks!
