### ISSUE TITLE
Naming Integers

### ISSUE THREAD

**Issue by paholg** [paholg/typenum#16]
I'm pretty happy with the names we have for unsigned integers and the type aliases, although I'm open to suggestions for changes.

For integers, this is what I'm thinking:

```rust
struct Positive<U: Unsigned>;
struct Negative<U: Unsigned>;
struct Zero;
```

Alternatively, we could do something like:

```rust
trait Sign {}
struct Positive;
struct Negative;
struct Zero;
impl Sign for [Positive, Negative, Zero] {}

struct Int<U: Unsigned, S: Sign>;
```

Finally, how do we want to name the aliases?

My thought right now is `..., IN2, IN1, I0, I1, I2, ...` but I don't really like the asymmetry between positive and negative.

Another option is `..., IN2, IN1, I0, IP1, IP2, ...`.

Any other ideas?

**Comment by llogiq** [comment]
How about `Mn`, ... `M2`, `M1`, `Z`, `P1`, `P2`, ... (where `Z` is for zero, `M`x is for -x and `P` x is for +x)?

However, the `I` prefix has the upside of being more easily recognizable.

**Comment by paholg** [comment]
I agree that the `I` prefix is good, but I like `N` for "Negative" more than `M` for "Minus".

I like the underscores, but I think it might be less clear than using a letter.

For the struct names, I'm thinking now
```rust
struct PInt<U: Unsigned>;
struct NInt<U: Unsigned>;
struct I0;
```
(with the necessity that `U` is never zero) which has the bonus that `I0` doesn't need to be an alias.

**Comment by llogiq** [comment]
That NonZero trait may also be useful elsewhere. I like your proposal.

**Comment by paholg** [comment]
It would be more useful if we weren't targeting stable. Using the optin_builtin_traits feature, we could do this:

```rust
pub trait NonZero {}

impl NonZero for .. {}
impl !NonZero for UTerm {}
```

then we could do an impl for `Unsigned + NonZero` and it would exclude `UTerm` for us, cleaning up a lot of code.

Doing something similar, I was able to overload multiplication and division in the way I wanted in dimensioned.

**Comment by paholg** [comment]
I've started playing with implementing integers, and as much as I like integer constants starting with `I` for conceptual clarity, it really hurts visual clarity.

Numbers like `I1198` are painful to read. I even have some trouble with `I1`; it just takes me a moment to process what it is.

My vote right now for constants is `P#` for positive, `N#` for negative, and I'm not sure what for zero.

We could alias `P0` and `N0` to both be zero, but I'm not a huge fan of that. We could also keep it as `I0`.

**Comment by llogiq** [comment]
I feel `I0` reads too much like IO. How about `IZero` or just `Zero` or even `Z`?

**Comment by paholg** [comment]
That's fair. How about `Z0`? It's a bit weird, but follows the format of the other numbers.

Should we alias `P0` and `N0` to be zero?

**Comment by llogiq** [comment]
I think if we have Z or Z0, there's no need for an alias, but I also see no harm in defining one.
