### ISSUE TITLE
Marking `Unsigned` as `'static`

### ISSUE THREAD

**Issue by tspiteri** [paholg/typenum#170]
Some [bytemuck](https://docs.rs/bytemuck) traits like [`Pod`](https://docs.rs/bytemuck/1/bytemuck/trait.Pod.html) have a `'static` constraint. When implementing such traits for types having an `Unsigned` type parameter, I have to add a `'static` constraint. For example

```rust
impl <T: 'static + Unsigned> Pod for MyType<T> {}
```

Since `Unsigned` should only be implemented for internal types, and all these types are `'static`, can the `Unsigned` types be marked as `'static`?

And if the answer is yes, are there any other marker traits that should receive the same treatment?

If the answer is yes, I could write a PR.

**Comment by paholg** [comment]
Sure! `Integer` and `Bit` could use the same treatment.
