### ISSUE TITLE
Unable to compile on Ubuntu Xenial with older glibc

### ISSUE THREAD

**Issue by TheDutchMC** [paholg/typenum#172]
Hey there.
I've run into the unfortunate situation of having to support an older version of Ubuntu, as per the title that is Xenial (16.04). Xenial ships with glibc 2.23, which is what I am limited to.

When compiling `typenum v1.13.0` it is failing on due to glibc being not on v2.29:
```
Caused by:
  process didn't exit successfully: `/app/librconsole/target/release/build/typenum-23fe1de9b8e7ca54/build-script-main` (exit code: 1)
  --- stderr
  /app/librconsole/target/release/build/typenum-23fe1de9b8e7ca54/build-script-main: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /app/librconsole/target/release/build/typenum-23fe1de9b8e7ca54/build-script-main)
```

Is there anything I can do about this, or is this something that is 'unfixable'?
Many thanks!

**Comment by TheDutchMC** [comment]
When enabling the `no_std` feature flag it does seem to compile fine. Though I dont think this is the most optimal solution

**Comment by paholg** [comment]
The `no_std` feature flag does nothing. I expect it made it work because it forced a rebuild.

That error usually occurs when you've compiled a crate with one version of glibc, but then try to run it with an older one.

Try `cargo clean` then building.

**Comment by TheDutchMC** [comment]
Thats what I thought too. I used a ubuntu:xenial docker image:
```dockerfile
FROM ubuntu:xenial
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update -y && apt-get install -y \
    gcc \
    curl \
    wget

RUN curl https://sh.rustup.rs -sSf | sh -s -- -y
RUN ln -s ${HOME}/.cargo/bin/* /usr/local/bin/
RUN rustup toolchain install stable-x86_64-unknown-linux-gnu
RUN rustup target add x86_64-unknown-linux-gnu

RUN mkdir -p /app
CMD cd /app/librconsole && cargo build --lib --release --target x86_64-unknown-linux-gnu
```

When I ran the container without the no_std feature flag, it would not compile and give the above mentioned error, but with the no_std flag it compiled and ran just fine. Not sure what's going on, but it works lol

**Comment by paholg** [comment]
Maybe there's some caching going on between your docker image and outside?

This line looks suspect to me, but I don't know a lot about building things with docker:

```
RUN ln -s ${HOME}/.cargo/bin/* /usr/local/bin/
```

**Comment by TheDutchMC** [comment]
Apologies for the late response.

That line you mentioned symlinks the cargo binaries to /usr/loca/bin, since for some reason it doesnt like to just source the env file provided, so the binaries arent found without the symlink.

I think the issue can be boiled down to an issue in my dependency tree, somehow. Actix-web is the only dependency declaring typenum as a nested dependency, so I'm not sure how.

Declaring the typenum dependencie manually seemed to have solved it, though I havent tried without the no_std flag, but you mentioned it shouldnt do anything anyways.

So I think this issue can be closed then, hopefully. Thanks for your time!
