### ISSUE TITLE
[feature-request] Adding a `const` field to `ToInt`

### ISSUE THREAD

**Issue by winestone** [paholg/typenum#178]
Hi, would there be any interest/objections for adding a `const` field to `ToInt`? Roughly something like this:

```diff
 pub trait ToInt<T> {
     fn to_int() -> T;
+    const INT_VALUE: T;
 }
```

This would allow the trait to be used in a `const fn` context.

I'm happy to make the change along with any testing/documentation/etc wanted.

**Comment by paholg** [comment]
I have no objections.
