### ISSUE TITLE
Has typenum diverged from tnfilt?

### ISSUE THREAD

**Issue by jacg** [paholg/typenum#180]
Here is an example of a rather disappointing interaction I've had with [`tnfilt`](https://crates.io/crates/tnfilt), where I paste a portion of an error generated by `typenum`:
```shell
echo 'PInt<UInt<UInt<UInt<UTerm, B1>, B1>, B0>>' | tnfilt     
PInt<UInt<UInt<UInt<UTerm, B1>, B1>, B0>>
```
Looking at the example provided by `tnfilt` itself, I notice that everything is qualified with `typenum::`. Adding these qualifications by hand and trying again, gives the altogether more satisfying
```shell
echo 'typenum::PInt<typenum::UInt<typenum::UInt<typenum::UInt<typenum::UTerm, typenum::B1>, typenum::B1>, typenum::B0>>' | tnfilt
typenum::PInt<U6>
```
As `tnfilt`s last commit dates from 30 months ago, I wonder whether something has changed in `typenum` (like the disappearance of the `typenum::` qualification in the errors) that has broken `tnfilt`.

**Comment by jacg** [comment]
A quick hack in `tnfilt` seems to fix the problem for my use case, so I've submitted [PR](https://github.com/auxoncorp/tnfilt/pull/1) in `tnfilt`.

**Comment by paholg** [comment]
I would assume it's the Rust compiler that has changed, not typenum. But thanks for opening that PR!
