### ISSUE TITLE
building with nix

### ISSUE THREAD

**Issue by mimoo** [paholg/typenum#183]
just as an FYI, but for some reason typenum requires libiconv to build, so in nix you can just import `pkgs.libiconv` in your `nativeBuildInputs`.

this might be useful to someone one day

**Comment by mimoo** [comment]
I can't remember what I was trying to do exactly, but I wasn't using the rustup package, maybe that's why?

**Comment by mimoo** [comment]
mmm, sorry for the confusion maybe I had messed up something on my end

**Comment by mimoo** [comment]
btw I think nix-shell is an older command that's deprecated in favor of more "flaky" commands no?

**Comment by paholg** [comment]
I think so, but it's the one I know how to use off-hand.
