### ISSUE TITLE
Subtraction

### ISSUE THREAD

**Issue by paholg** [paholg/typenum#2]
Subtraction of `UInt`s does not currently work as it should. It needs to be changed so that `UInt<UTerm, B0>` doesn't show up anywhere, and is instead replaced with simply `UTerm`.

This may require an O(N^2) replacement after subtraction takes place, which would be unfortunate.

Also, need to think about how `UInt` subtraction can be used for `Int` and if the current method causes issues.

**Comment by llogiq** [comment]
Fwiw, I still think that this shouldn't be O(N²), unless you count N as the number of bits.

**Comment by paholg** [comment]
Uh, yeah, I was thinking in terms of number of bits. So that's really not that bad.

I guess I'll think about what should be more optimal ... doing the computation after (replacing all `UInt<UTerm, B0>` with `UTerm` until we reach a `UInt<UTerm, B1>`) or subtracting by reducing both operands by 1 until complete.

Thinking about it, the first way will certainly be faster, as it actually takes advantage of the fact that we're using binary, so I'll just go ahead and do that.

**Comment by paholg** [comment]
My initial attempt at trimming `UInt<UTerm, B0>`s didn't pan out. Or at least I don't see how it can work.

New method: After subtraction, I will invert the number, remove the trailing zeros, then invert it again.

Ex:
```
  10010 - 10000
= 00010
= 01000 (by inversion)
= 01 (remove trailing zeros)
= 10 (by inversion)
```

**Comment by paholg** [comment]
Subtraction may yet pose an issue for signed `Int`s, but this should be good.
