### ISSUE TITLE
Signed integer binary operations

### ISSUE THREAD

**Issue by paholg** [paholg/typenum#27]
How do we want to handle the sign for binary operations for integers? E.g. what should be the result of -3 & 5?

The easy solution is to just not implement them ... I feel like if you want to do that kind of stuff, unsigned numbers are there for you.

Another question is, should we implement Not for unsigned integers? It would be easy enough to do, but a bit weird. Not makes sense when you have something of a set length, but for our `UInt` implementation, there are never leading zeros, so I think implementing Not would make some basic logical things fail. Writing this has pretty much convinced me that we shouldn't do it.

**Comment by llogiq** [comment]
I don't think we have not for UInts, do we? Without a fixed number of bits, it makes little sense (the best we *could* do would be Xor((highest bit << 1) -1).

**Comment by paholg** [comment]
Yeah, I guess it's pretty clear we `Not` makes no sense.

So, no `Not` for unsigned or signed integers, and no `And`, `Or`, or `Xor` for signed integers.

**Comment by llogiq** [comment]
Why not `And`, `Or` or `Xor`? They're all usefully defined. Just treat the Sign as another Bit, and forward the rest of the operation to the UInt implementation.

**Comment by llogiq** [comment]
I'll go do that.

**Comment by paholg** [comment]
What should `P1 & N1` be?

Normally, signed integers are handled with two's complement, so sign information is stored in the bits.

We don't do that; sign is extra information. We could decide that positive is 1 and negative is 0, but that just seems to arbitrary to me. We could also decide that negative is 1 and positive is 0. Also, doing logical operations with our integers will act very differently than any other integers that anyone has used. That seems bad to me.

**Comment by llogiq** [comment]
Negative is 1, positive is 0. This works basically as a variable-length two's complement. In fact, unless you count on overflow, this will work *exactly* as normal signed integer operations.

One wrinkle when implementing this is that the result of a `BitAnd` or `BitXor` can be zero, which means we need to distinguish this case from the `NonZero` case.

**Comment by paholg** [comment]
For example, in two's complement, -3 is 111...11101, so -3 & 3 = 1, whereas for us -3 & 3 would be 3, if implemented naively (as just `NInt<Ul> & PInt<Ur> = PInt<Ul & Ur>`).

I suppose we could be more clever about the implementation, so that it mimics two's complement, but that also seems strange, as that's not how we represent our numbers.

We also face a similar issue with shift-right. Shifting left, I believe, should have no difference between our numbers and two's complement, but e.g. -3 >> 1 = -2. Do we implement it naively, mimic two's complement, or just leave it out?

My leaning is to leave out any operation if it's not clear what the result should be.

Part of that may be because I've never found a need to perform logical operations on signed integers, and I can think of even less use for it at the type level.

**Comment by llogiq** [comment]
Yeah you're probably right. Closing this.
