### ISSUE TITLE
It is really incovenient to define numbers

### ISSUE THREAD

**Issue by fizyk20** [paholg/typenum#3]
For example, to define an unsigned number 97, one has to use the code:
```rust
type P97 = UInt<UInt<UInt<UInt<UInt<UInt<UInt<UTerm, B1>, B1>, B0>, B0>, B0>, B0>, B1>;
```

Wouldn't it be better to define `UInt` like:
```rust
type UInt<U: Unsigned, B: Bit> = (U, B);
```
instead of a custom struct? Then, the above notation would still be valid, but it could also be written like:
```rust
type P97 = (((((((UTerm, B1), B1), B0), B0), B0), B0), B1);
```
which, I think, is more readable.

If it's even possible, a macro would also solve this problem (so one could for example write `uint!(97)`), but I'm not sure if Rust macro system allows for something like that (and if it does, I have no idea how to write it).

**Comment by paholg** [comment]
I tend to agree. The issue with using just a tuple, though, is that you no longer have a struct and can only impl traits that have been defined in the same crate.

It might be okay to just accept that we can't impl other traits, but I chose flexibility over ease of use for now.

A workaround would be to define UInt so it's used as so: `type U97 = UInt<(((((((UTerm, B1), B1), B0), B0), B0), B0), B1)>;`

This would allow other traits to be implemented for the `UInt`, but would still require custom traits to be used recursively.

I had thought of a macro as well; I'm not sure how difficult it will be to write.

**Comment by fizyk20** [comment]
>The issue with using just a tuple, though, is that you no longer have a struct and can only impl traits that have been defined in the same crate.

Oh, right, I hadn't thought of that; this is a good reason.

>I had thought of a macro as well; I'm not sure how difficult it will be to write.

The main issues with a macro, as I understand the Rust macro system, is that it can't really interpret its parameters as values. I don't know of any way to accept numeric parameters in macros and use them in arithmetic expressions, as would be needed here. Of course, it might only be my limited knowledge of the matter, but I tried googling and it yielded no results.

The best I can come up with is something like `uint!(1, 0, 1)` yielding `UInt<UInt<UInt<UTerm, B1>, B0>, B1>`.

**Comment by paholg** [comment]
Yeah, I think you're right. I imagine a syntax extension would be able to do it, but that's more than I want to do right now. In any case, a `uint!(1, 0, 1)` macro would solve the convenience issue as much as just using tuples would, so I'll go ahead and do that.

**Comment by paholg** [comment]
Ah, one issue is that type macros are still experimental, which kills usability on stable. Hmm.

**Comment by fizyk20** [comment]
Ouch. I didn't know that, but that's not good.

Also, syntax extensions only work on nightly, too, I think.

**Comment by paholg** [comment]
Yeah, type macros are really new. I'm not exactly sure how the development cycle works, but I think once they stop being experimental in nightly, they'll migrate to the next beta build, so they'd be months out from getting to stable.

Using the [syntex](https://github.com/serde-rs/syntex) crate, syntax extensions can be used on stable, but I'm not sure if they can be used as types without the experimental feature.

It would be nice if there were a lint to say "hey only do this stuff if you're on nightly" so I could make the macros but keep stable compatibility, but I haven't found a way to do it.

**Comment by paholg** [comment]
For what it's worth, I've now aliased all the numbers up to `U128` as well as many of the powers of 2 after.

**Comment by fizyk20** [comment]
Oh, nice. That will help, thanks :)

**Comment by paholg** [comment]
And... now we generate aliases for unsigned integers through 1024, as well as all powers of 2 and 10 (below 2^64), and the same and all the negative versions for signed integers.

It will be some time before we can do type macros on stable, so I'm gonna call this "as good as we can get" for now and close it.
