### ISSUE TITLE
Quickcheck vs. typenum?

### ISSUE THREAD

**Issue by llogiq** [paholg/typenum#30]
I thought a bit about our tests and how they miss a good number of useful cases. It would be insanely great to have quickcheck on it, but the way quickcheck works is by instantiating more or less random stuff at runtime, and we do compile-time. So perhaps we may want to use either create a plugin (nightly only, though) or use the rustc bindings of [compiletest-rs](https://crates.io/crates/compiletest_rs) to create our compile-time tests at runtime and enable quickcheck-like functionality. Then we'd only need to set up our tests so that they fail with an appropriate error.

**Comment by paholg** [comment]
This sounds like a great idea. Our test could just write out to a file, and then try to compile it.

**Comment by llogiq** [comment]
Exactly.

**Comment by paholg** [comment]
So I've created a tests branch with a family of functions for doing runtime tests.

Running them looks like this (from tests/sample.rs)

```rust
build::uint_binary_test(7, "Div", 2, 3);
build::uint_unary_test("SizeOf", 17, 5);

build::int_binary_test(7, "Add", 2, 9);
build::int_unary_test("Neg", 3, -3);
```

Where the last argument to each is what the result should be.

These functions each create a new rust project that performs said operation, and then attempt to compile it, panicking if it fails.

I figure these should be useful for building a comprehensive testing suite.

Given your experience, you want to take it the rest of the way?

**Comment by paholg** [comment]
Looking again, each of those function calls takes nearly half a second, so we probably want to do it differently. Like, make a single rust project that runs all the tests.

**Comment by llogiq** [comment]
Yeah, we don't need the quickcheck run; what we need is to construct random values as input to our code. Then we build a huge semi-random program to feed into rustc and run it once to probably get a lot of errors/warnings.

**Comment by paholg** [comment]
I've been playing with it, and I have something that works, but it's really slow. The current test I have takes about 40 seconds on my laptop, and almost all of that is generating the code for the test that only takes about 3-4 seconds to compile.

I'm not sure if I should work on optimizing it or just try a different approach.

**Comment by llogiq** [comment]
Why is the code generation so slow anyway? I'd have thought it should take less time to generate than to compile, not the other way round.

One thing I see in your code is a lot of allocation, which is going to be quite inefficient. Perhaps we want to create a Test structure that implements `fmt::Display` and then just `write!(..)` it to disk. That way we should get rid of most allocations. Something like (untested):
```
enum UIntCode {
     UTermCode,
     UZeroBit(UIntCode),
     UOneBit(UIntCode),
}

impl fmt::Display for Point {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        match *self {
            UTermCode => write!(f, "UTerm"),
            UZeroBit(ref inner) => { 
                write!(f, "UInt<");
                write!(f, "{}", inner);
                write!(f, ", B0>");
            },
            UOneBit(ref inner) => { 
                write!(f, "UInt<");
                write!(f, "{}", inner);
                write!(f, ", B1>");
            }
        }
    }
}

gen_uint(u: usize) -> UIntCode {
    let mut result = UTermCode;
    let mut x = 1usize << 63;
    while x > u { x = x >> 1 }
    while x > 0 {
         result = if x & u == 1 { UOneBit(result); } else { UZeroBit(result); }
    }
}
```

**Comment by paholg** [comment]
That sounds good; I'll work on implementing it. I was just going for something that works, not thinking that performance was going to be a problem. I still don't really get why it is; generating something like 500 lines and writing it is taking ~30 seconds.

**Comment by llogiq** [comment]
Also you should wrap the `File` in a `BufWriter` – I've reduced runtime by 30% in the fasta-redux benchmark (well before Veedrac came and made it 5×faster), and that was only writing to stdout.

**Comment by paholg** [comment]
That one change took me from ~40 seconds to ~13 on my laptop for `cargo clean && time cargo test` (and down to ~6s on my desktop ... not sure what it was before there).

Good call!

I see more places we can do better, too.

**Comment by paholg** [comment]
Getting rid of iterators and just writing the various tests as we loop through the numbers has sped it up significantly.

On my laptop, (with a clean before each command), `cargo build` takes 3.7s, `cargo test` takes 12.1s, and running `cargo run` in the generated repo takes 5.5s.

So, unless I'm not accounting for something, generating the tests takes 12.1s - 3.7s - 5.5s = 2.9s, which is a lot better (just under 1/4 of the total time), but still could maybe be improved.

**Comment by llogiq** [comment]
Strange, I thought it would make more of a difference. Btw. rethinking the numbers idiom, we can actually just store the u64 and use the bit twiddling while writing.

If you commit your current code, I can have a look.

**Comment by paholg** [comment]
Just pushed it.

**Comment by llogiq** [comment]
Cool. Closing this.
