### ISSUE TITLE
Version 1.0.0

### ISSUE THREAD

**Issue by paholg** [paholg/typenum#31]
I'd like to get this to a place we can call stable soon, then we can start telling people to use it. Also I'd like to use it for dimensioned.

I think we're almost there. As far as I can tell, the only operator we're missing is `Rem`, which we can add to the division code already there easily enough. I should have time to do that today.

Adding the quickcheck / compiletest stuff would go a long way to ensuring that our code does what we think it does.

I really can't think of anything (other than possibly fixing bugs) that we might want to implement that would cause breaking changes. I'd like to refactor division so it's faster, but that won't break anything.

Thoughts?

**Comment by paholg** [comment]
We also need better comments, with examples sprinkled throughout. I will likely start working on this soon.

**Comment by llogiq** [comment]
(I just updated your comment to make it an actual clickable todo list).

**Comment by paholg** [comment]
Sweet. I didn't know that was a think in markdown.

**Comment by llogiq** [comment]
It's a github extension.

**Comment by paholg** [comment]
Ah, that makes sense.

**Comment by paholg** [comment]
I think I've got the documentation in a pretty decent state. Would you mind taking a look at it, @llogiq?

After that, I guess we're ready for version 1.0 unless you can think of anything else we should do first.

**Comment by llogiq** [comment]
I think our README.md needs some love. Apart from that, the docs look good to me.
