### ISSUE TITLE
to_ordering should be inline

### ISSUE THREAD

**Issue by bluss** [paholg/typenum#39]
This is a micro issue, but the  `to_ordering` methods should be marked `#[inline]`, since they are not generic, they cannot otherwise be inlined.

**Comment by bluss** [comment]
Same for all the methods in `impl Integer for Z0` by the way.

**Comment by llogiq** [comment]
I'm on it.

**Comment by bluss** [comment]
same with `impl Unsigned for UTerm`.  Should eliminate some function calls

**Comment by llogiq** [comment]
Yeah. Unfortunately, I get a compiler error with current nightly...

**Comment by llogiq** [comment]
Yeah, I was kinda automatically adding it anyway.

**Comment by llogiq** [comment]
Thanks for pointing that out, @bluss

**Comment by llogiq** [comment]
@paholg should we bump the version to 1.0.1?

**Comment by bluss** [comment]
great!

**Comment by paholg** [comment]
Huh, I figured the compiler would take care of that. Yeah let's bump it.

**Comment by bluss** [comment]
It can if you compile with LTO, not otherwise. `#[inline]` apart from bumping affinity for inline slightly, it makes sure a method is emitted in the crate metadata and can be cross crate inlined (but this is already happening for a generic method).
