### ISSUE TITLE
`::to_usize` has fatal performance

### ISSUE THREAD

**Issue by hauleth** [paholg/typenum#44]
Using `Unsigned::to_usize()` made Octavo 875% slower. Could it be any better?

**Comment by paholg** [comment]
I assume you mean compile time and not run time? It *should* not affect run time much at all.


The function `to_usize()` itself should be fast to compile, but what it does is force whatever type you're calling it on to be evaluated. I would guess that without it, nothing else is forcing the type to be evaluated.

For typenum in general, division and modulo do not currently scale properly and can take a long time to compile, so if you're using either of those, that may be the issue.

If you show me where you're using it, I can play around and try to find the issue.

**Comment by hauleth** [comment]
No, runtime. `::to_usize` wasn't inlined and was called all the way to end each time.

**Comment by paholg** [comment]
Weird. That should definitely be fixable; I'll play with it and see if I can come up with anything.

**Comment by paholg** [comment]
Aha! I had forgotten to inline a couple functions. When built with optimizations, my admittedly rudimentary test now shows that `to_usize` takes virtually no run time.

I have pushed this change and updated the version to 1.0.2. Please let me know whether it's fixed it for you.

**Comment by hauleth** [comment]
Still 5x-6x performance drop. Investigating if it is caused by this typenum.

**Comment by hauleth** [comment]
It is not fault of `typenum`. Closing for now as solved.
