### ISSUE TITLE
Names for operator aliases

### ISSUE THREAD

**Issue by paholg** [paholg/typenum#48]
After seeing [this](https://www.reddit.com/r/rust/comments/3vkj5r/its_2015_why_do_we_still_write_insecure_software/cxoy7q7) comment on reddit, which suggests defining aliases like

```rust
type Plus<A, B> = <A as Add<B>>::Output;
```

I would like to play with adding such aliases to typenum.

What names should we use? The full list of operators we have is

- Ones we've defined: `Same`, `Pow`, `Cmp`,
- Bit operators: `BitAnd`, `BitOr`, `BitXor`, `Not`, `Shl`, `Shr`
- Arithmetic operators: `Add`, `Sub`, `Mul`, `Div`, `Rem`

For arithmetic, I was thinking `Sum`, `Difference` (`Diff`?), `Product` (`Prod`?), `Quotient` (`Quot`?), `Remainder` or `Modulo` / `Mod`.

As an aside, it annoys me that `Rem` is not called `Mod`, it is inconsistent with the other operator names. Add, subtract, multiply, divide, remainder: one of these is not like the others.

For some of the the bit operators, we could do `And`, `Or`, and `Xor` (leaving off the Bit), not sure about the others though. I'm not sure I really like that, but can't think of alternatives at the moment.

For `Pow`, we could do `Exp`. I'm not sure how useful an alias for `Same` would be, but might as well do one if we're doing the others. For `Cmp` I'm not sure of a good name. `Compare`?

**Comment by droundy** [comment]
I would think that a few low powers might be useful with their own names:
Square, Cube.
