### ISSUE TITLE
"Overflow evaluating the requirement" in the latest nightly

### ISSUE THREAD

**Issue by netvl** [paholg/typenum#59]
I'm getting this error when compiling with the latest nightly:
```rust
   Compiling typenum v1.3.0 (file:///tmp/typenum)
error: overflow evaluating the requirement `uint::UInt<_, _> : private::PrivateCmp<uint::UInt<_, _>, Equal>` [E0275]
src/lib.rs:1:1: 1:1 note: consider adding a `#![recursion_limit="128"]` attribute to your crate
error: aborting due to previous error
error: Could not compile `typenum`.
```
Raising recursion limit, as suggested, does not work.

**Comment by paholg** [comment]
It seems that some change with the compiler does not like how I do division. Unfortunately that code is ...ugly. I should have time to work on it later today, and hopefully figure it out.

**Comment by paholg** [comment]
My attempts to refactor to make this work have failed so far. My hope is that it will just be fixed by fixes to nightly without having to touch typenum at all.

It is just some of the the division code that won't compile. If you need this to work on nightly now, and don't need to use division, I can add a feature flag to disable division.

Let me know if you'd like that.

**Comment by netvl** [comment]
@paholg well, I encountered this problem when liboctavo which I wanted to use did not compile (its digest crate depends on typenum). For the time being I switched to another crate, so I'm actually not blocked by this problem now.

Since it appears that it worked before, maybe it makes sense to file an issue to the Rust issue tracker? I believe regressions such as this will be fixed with higher priority for the next release/beta.

**Comment by paholg** [comment]
Yeah I was planning on filing an issue, just hoping to get some concise code that would reproduce it first to make the issue better.

I'll play around more and try to get typenum working with rust as-is as well, it's just what I've tried so far has yielded nothing.

**Comment by paholg** [comment]
Sorry it took me so long to get around to it, but I've located and fixed the issue. It should be published momentarily.
