### ISSUE TITLE
Cleanup where clauses?

### ISSUE THREAD

**Issue by paholg** [paholg/typenum#65]
So, I had a thought that may or may not make any sense.

Let's say we want to make a trait that doubles type numbers. That might look like this

``` rust
trait Double {
    type Output: Unsigned;
}

impl<U> Double for U where U: Unsigned + Mul<U2>, Prod<U, U2>: Unsigned {
    type Output = Prod<U, U2>;
}
```

They're not _too_ bad there, but the where clauses that accompany typenum can get really out of hand, to the point of discouraging people from using it at all.

I have no experience with procedural macros, but I'm wondering if it might be possible to have one that inspects what happens in the impl and inserts the appropriate `where` clauses, so the above `impl` could be replaced with something like this:

``` rust
#[typenum]
impl<U: Unsigned> Double for U {
    type Output = Prod<U, U2>;
}
```

The compiler knows exactly what `where` clauses to throw in already, it just makes us do it.

@llogiq, you have experience with procedural macros. Is this at all reasonable, or am I asking way too much from the macro system?

**Comment by llogiq** [comment]
I'm currently on hiatus (+mobile) so I'll be brief. With procedural macros 1.0, it is possible to extend/replace arbitrary code provided it lives inside a code unit (crate/mod/fn) that is annotated. E.g.

`#[typenum] mod too { type PlusThree<T:  Unsigned> = $(T+3) }`
