### ISSUE TITLE
Why prevent instanciation and why do operator overloads diverge ?

### ISSUE THREAD

**Issue by sebcrozet** [paholg/typenum#67]
Hi ! Is there a particular reason why `UInt` et al. are not instanciable (as ZSTs) and why the operator traits like `Mul`, `Div`, etc. diverge with `unreachable!()` ?

Allowing that could be very helpful for type inference in generic code. For example, currently I can do the following:

```rust
fn foo<T: Unsigned>() {
}

fn main() {
    foo::<Sum<U10, U23>>();
}
```

If they were instanciable, I could instead do:
```rust
fn foo<T: Unsigned>(tag: T) {
}

fn main() {
    let u10 = U10::new();
    let u23 = U23::new();
    foo(u10 + u23);
}
```

While for this specific example the second option may seem more verbose, this becomes much more useful when the expression becomes more complicated (and when instead of, say `U10` and `U23`, you have type parameters).

**Comment by paholg** [comment]
To answer your second question first, operators diverge because they have to. As you've pointed out, the types are uninstantiable, so the only options are to have the function diverge or create new traits without functions. If they were instantiable, we could make the functions not diverge.

For your first question, I'm not sure I have a satisfying answer. All my use of typenum (and all of my envisioned use) involves code that is generic over numbers; things like `Dimensioned` and `GenericArray` where the actual numbers are hidden away beneath some layers, for users to never interact with directly.

That said, I can't think of a downside, so if you'd find instantiable type numbers useful, I'd accept a PR. It should be a fairly straight-forward change.

**Comment by llogiq** [comment]
IIRC we used uninstantiable types to prevent inadvertent instantiation – we wanted to be sure that the compiler will erase all of it to have zero runtime overhead.

**Comment by sebcrozet** [comment]
Well, ZSTs are supposed to introduce no overhead. To site the rust [book]():

> Rust largely understands that any operation that produces or stores a ZST can be reduced to a no-op. First off, storing it doesn't even make sense -- it doesn't occupy any space. Also there's only one value of that type, so anything that loads it can just produce it from the aether -- which is also a no-op since it doesn't occupy any space.

Here are more details about my use-case in the context of my current redesign of [nalgebra](https://github.com/sebcrozet/nalgebra). Let say I want to declare a dynamically-allocated matrix with a size that may either be known at compile-time or at runtime. Typically, one would create two structures:

```rust
struct DynamicMatrix {
    data: Vec<f32>,
    nrows: usize,
    ncols: usize
}

struct StaticMatrix<NRows: Unsigned, NCols: Unsigned> {
    data: Vec<f32>,
    _phantoms: PhantomData<(NRows, NCols)>
}
```

But I don't like having two different structures because that would imply implementing matrix operations twice (well, we could use macros, or some trait, but for the sake of the example, just say that we don't).

A simple way to unify both structures is something like the following:
```rust
trait Dimension {
    fn value(&self) -> usize;
}

struct Dynamic {
    dim: usize
}

impl Dimension for T where T: Unsigned {
    fn value(&self) -> usize {
        T::to_usize()
    }
}

impl Dimension for Dynamic {
    fn value(&self) -> usize {
        self.dim
    }
}

struct Matrix<NRows: Dimension, NCols: Dimension> {
    data: Vec<N>,
    nrows: NRows,
    ncols: NCols
} 
```

Here, a `Matrix<U1, U3>` will automatically be equivalent to the `StaticMatrix` of this comment because `nrows` and `ncols` will just be ZSTs. On the other hand, writing `Matrix<Dynamic, Dynamic>` will automatically specialize to the `DynamicMatrix` with two usize-s to store the dimensions. Being able to do that requires, at some point, to be able to instanciate typenum's type-level integers.

Currently, my workaround is to initialize them with `mem::uninitialized()` but that's obviously ugly. I'll create a PR; it should be straightforward indeed.

**Comment by droundy** [comment]
I agree that instantiating type level numbers does seem like a nice idea.
I do wonder, however, to what extent this could remove any performance
benefits for statically sized arrays.

**Comment by paholg** [comment]
@droundy What do you mean? I can't see how allowing the types to be instantiated would slow down anything that doesn't instantiate them. Or perhaps I misunderstand?

**Comment by droundy** [comment]
I wasn't meaning to suggest that instantiation would slow code down, but
rather that possibly using instantiation with traits to enable code to work
with either dynamically or statically sized arrays could remove any
performance benefit of statically sized arrays.

**Comment by sebcrozet** [comment]
@droundy In the use-case I presented, using matrices with dimensions known at compile-time will not have any significant performance benefit compared to dimensions known at run-time. The point of using dimensions known at compile-time is to be able to detect (at compile-time) mismatched dimensions when, e.g., trying to multiply two matrices. I still want the user to be able to use `Dynamic` dimensions because sometimes you can't know them at compile-time.

When dimensions are known at compile-time, it would be a shame to waste two `usize` if you already know their values through the type parameters. This applies to matrices, but that was just one example I gave. In my case, it also applies to more ligthweight objects like matrix slices which do not own their data buffer (instead of a `Vec`, they contain a `*const f32`). In that case, two useless `usize` in the slice data structure become a significant memory overhead.

**Comment by droundy** [comment]
Ah, thanks Sebastian, that clears things up for me.
