### ISSUE TITLE
Add member functions for custom type operators?

### ISSUE THREAD

**Issue by paholg** [paholg/typenum#71]
Now that we have instantiable zero-sized types and operators that don't diverge, it would be nice to have the same for the operators that we define, like this one:

``` rust
pub trait Pow<Exp> {
    type Output;
}
```

Unfortunately, this is a breaking change. I find it _very_ unlikely that anyone besides me has implemented these traits for anything, though, and it's a small break; one could just put in the divergent function to restore functionality.

I suppose, if this is an acceptable breakage, it would have made the most sense to do before pushing to version 1.4.0, but I got excited....

The full list of traits affected is: `Same`, `Pow`, `Cmp`, and `Len`.

**Comment by paholg** [comment]
As I think about it, `Same` is implemented for all types in typenum, so adding a function to it can't break anything, and I *just* added `Len`, which leaves only `Pow` and `Cmp` for potential breaking changes. I think that should be okay.

**Comment by droundy** [comment]
I concur.
