### ISSUE TITLE
`Cmp` and trait inheritance

### ISSUE THREAD

**Issue by jonysy** [paholg/typenum#77]
`Cmp<N, Output = Greater>` should implement `Cmp<M, Output = Greater>` where `N > M`.

The following code snippet results in an error at compile time:

```rust
use typenum::{consts, Cmp, Greater};

struct Foo<N>(N);

impl<N> Foo<N> where N: Cmp<consts::U0, Output = Greater> {
    fn foo1(&self) -> u8 { 1 }
} 

impl<N> Foo<N> where N: Cmp<consts::U1, Output = Greater> {
    fn foo2(&self) -> u8 { 
        self.foo1 
             ^^^^the method `foo1` exists but the following trait bounds were not satisfied: `N : typenum::Cmp<typenum::UTerm>`
    }
} 
```

Since `1` is greater than `0`, `foo1` should be callable from `Foo<T>` where `T >= 1`.

**Comment by paholg** [comment]
This is a larger issue with typenum (and, I imagine, any library that engages in similar type-level shenanigans). Basically, you cannot use any functionality without telling the compiler that you can.

You can make your code work by changing your `where` clause from

```rust
where N: Cmp<consts::U1, Output = Greater>
```

to

```rust
where N: Cmp<consts::U1, Output = Greater> + Cmp<consts::U0, Output = Greater>
```

I believe that I will be able to fix this with specialization over associated types, but not before. It seems to be undecided whether this will ever be added to the language.

It is also possible that upcoming type-system changes will fix it for us, but I don't know enough details of them to be able to guess how likely that might be.

**Comment by jonysy** [comment]
No worries 👍 

> It is also possible that upcoming type-system changes will fix it for us..

Are you referring to the RFCs based around type-level numbers?

**Comment by paholg** [comment]
@jonysy While that would fix the issue by obsoleting typenum, I was referring to this: http://smallcultfollowing.com/babysteps/blog/2017/01/26/lowering-rust-traits-to-logic/.

I would be surprised if those changes directly fixed these issues, but they may open up new opportunities to do so.
