### ISSUE TITLE
Compute the Min and Max of two integers.

### ISSUE THREAD

**Issue by sebcrozet** [paholg/typenum#79]
It could be useful to be able to write something like `Min<A, B>` where `A` and `B` are two type-level integers. This would be a type alias that translates to the type representing the smallest value among `A` and `B`.

My use-case is to be able to extract the smallest square submatrix of a matrix. This would for example look like:

```rust
fn squarify<A, B>(matrix: Matrix<f32, A, B>) -> Matrix<f32, Min<A, B>, Min<A, B>>
where A: Unsigned + MinTrait<B>,
      B: Unsigned
{ ...}
```

**Comment by paholg** [comment]
That seems easy enough; I should be able to whip it up sometime today.

**Comment by paholg** [comment]
Version 1.7.0 is now on crates and has these traits.

**Comment by sebcrozet** [comment]
Cool, thanks !
