### ISSUE TITLE
Abs type operator

### ISSUE THREAD

**Issue by programble** [paholg/typenum#84]
Should there be an `Abs` type operator for getting the absolute value of signed integers?

- `Z0` -> `U0`
- `PInt<U>` -> `U`
- `NInt<U>` -> `U`

It seems straight forward and I pretty much have a PR ready, but is there an existing way to do this that I'm missing?

**Comment by paholg** [comment]
Sounds reasonable. It might make more sense to keep it an integer, e.g. `NIunt<U>` -> `PInt<U>`, though, so the "type" doesn't change. You wouldn't expect `-3i32.abs()` to give you `3u32`.
