### ISSUE TITLE
Result of invalid computation.

### ISSUE THREAD

**Issue by paholg** [paholg/typenum#9]
When we subtract `UInt`s such that the result would be negative, we can either have a type error (the error is something like "the trait `Sub<RHS>` is not implemented for the type `LHS`"), or we can return a special `Underflow` type (which I do not envision implementing `Unsigned` for).

Similarly, when dividing non-divisible things, we can error out or return a `Fraction` type.

I'm not sure which is better. Thoughts, @llogiq?

**Comment by llogiq** [comment]
I think the types should not mix (apart perhaps from explicit cast operations).

Invalid operations should error out.

**Comment by paholg** [comment]
That's fair. I guess I shouldn't except people to want to do compile-time error propagation.
