### ISSUE TITLE
Overflow for generics

### ISSUE THREAD

**Issue by porky11** [paholg/typenum#91]
Simple example:
```
pub fn exp2<N: Unsigned+IsLess<U16>>() -> u32 {
    <<U2 as Pow<N>>::Output as Unsigned>::to_u32()
}
```
What I really want to do is creating struct using generic array containing `N²` elements

**Comment by paholg** [comment]
Your function computes `2^N`, which may be why you're seeing an overflow.

**Comment by paholg** [comment]
Feel free to reopen if you feel this is still a problem.
