### ISSUE TITLE
Creating a trait alias for generic bounds

### ISSUE THREAD

**Issue by Limeth** [paholg/typenum#93]
Hello! I am trying to use this `bit_array` crate that basically provides a stack-allocated array of bits using your excellent `typenum` crate, but I've run into a problem. I'd like to make a shorthand for the `NBits` generic argument, so I don't have to copy all of those generic bounds anytime I create a function: https://goo.gl/L8qQCm
This is my current code: https://goo.gl/oTR64e
I tried to make a trait with those bounds and a blanket impl for that trait. Unfortunately, I am getting these errors that I just can't wrap my head around: https://hastebin.com/hafaqovize
May I kindly request your feedback on this problem?

**Comment by WaDelma** [comment]
My experience indicates that you cannot remove the need of copy pasting bounds like these: `<T as Add<<B as BitsIn>::Output>>::Output: Sub<typenum::B1>`.
All normal trait bounds (eg. `T: Unsigned`) can be moved to one trait.

**Comment by Limeth** [comment]
That's a shame. I'll have to resort using a regular old primitive unsigned integer, then. Thanks.
