### ISSUE TITLE
Policy on integer algorithms to include in this crate?

### ISSUE THREAD

**Issue by dcrewi** [paholg/typenum#97]
I submitted a PR for integer square roots. I also implemented greatest common divisor but at some point additional algorithms belong in a different crate. GCD is sufficiently non-basic that I questioned whether to add it. Is there a line?

**Comment by paholg** [comment]
I'm not sure. Someday, integer generics will be added to the compiler, so this crate has a finite lifespan. Or maybe when that happens, it can pivot to just providing such algorithms at compile-time.

Maybe it would be worth putting more advanced algorithms in a separate module, but given that you're only proposing one, that seems overkill.

If you make a GCD PR, I would happily accept it.
